openapi: 3.0.3
info:
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.11
servers:
- url: https://petstore3.swagger.io/api/v3
tags:
- description: Everything about your Pets
  externalDocs:
    description: Find out more
    url: http://swagger.io
  name: pet
- description: Operations about user
  name: user
- description: Operations about order
  name: order
- description: Operations about category
  name: category
- description: Operations about product
  name: product
paths:
  /category:
    get:
      description: Returns list of categories
      operationId: get_category_list
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Category'
                type: array
            application/xml:
              schema:
                $ref: '#/components/schemas/Category'
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Category not found
      summary: Get list of all categories
      tags:
      - category
      x-openapi-router-controller: openapi_server.controllers.category_controller
    post:
      description: Add a new category to the store
      operationId: add_category
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
          application/xml:
            schema:
              $ref: '#/components/schemas/Category'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Category'
        description: Create a new category in the store
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
            application/xml:
              schema:
                $ref: '#/components/schemas/Category'
          description: Successful operation
        "405":
          description: Invalid input
      summary: Add a new category to the store
      tags:
      - category
      x-openapi-router-controller: openapi_server.controllers.category_controller
    put:
      description: Update an existing category by Id
      operationId: update_category
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
          application/xml:
            schema:
              $ref: '#/components/schemas/Category'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Category'
        description: Update an existent category in the store
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
            application/xml:
              schema:
                $ref: '#/components/schemas/Category'
          description: Successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Category not found
        "405":
          description: Validation exception
      summary: Update an existing category
      tags:
      - category
      x-openapi-router-controller: openapi_server.controllers.category_controller
  /category/{category_id}:
    delete:
      description: delete a category
      operationId: delete_category
      parameters:
      - description: Category id to delete
        explode: false
        in: path
        name: category_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
            application/xml:
              schema:
                $ref: '#/components/schemas/Category'
          description: successful operation
        "400":
          description: Invalid category value
      summary: Deletes a category
      tags:
      - category
      x-openapi-router-controller: openapi_server.controllers.category_controller
    get:
      description: Returns a single category
      operationId: get_category
      parameters:
      - description: ID of category to return
        explode: false
        in: path
        name: category_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
            application/xml:
              schema:
                $ref: '#/components/schemas/Category'
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Category not found
      summary: Find category by ID
      tags:
      - category
      x-openapi-router-controller: openapi_server.controllers.category_controller
    x-python-connexion-openapi-name: "/category/{categoryId}"
  /order:
    get:
      description: Returns list of orders
      operationId: get_order_list
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Order'
                type: array
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Order not found
      summary: Get list of all orders
      tags:
      - order
      x-openapi-router-controller: openapi_server.controllers.order_controller
    post:
      description: Add a new order to the store
      operationId: add_order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/xml:
            schema:
              $ref: '#/components/schemas/Order'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Order'
        description: Create a new order in the store
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
          description: Successful operation
        "405":
          description: Invalid input
      summary: Add a new order to the store
      tags:
      - order
      x-openapi-router-controller: openapi_server.controllers.order_controller
    put:
      description: Update an existing order by Id
      operationId: update_order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/xml:
            schema:
              $ref: '#/components/schemas/Order'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Order'
        description: Update an existent order in the store
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
          description: Successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Order not found
        "405":
          description: Validation exception
      summary: Update an existing order
      tags:
      - order
      x-openapi-router-controller: openapi_server.controllers.order_controller
  /order/{order_id}:
    delete:
      description: delete a order
      operationId: delete_order
      parameters:
      - description: Order id to delete
        explode: false
        in: path
        name: order_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
          description: successful operation
        "400":
          description: Invalid order value
      summary: Deletes a order
      tags:
      - order
      x-openapi-router-controller: openapi_server.controllers.order_controller
    get:
      description: Returns a single order
      operationId: get_order
      parameters:
      - description: ID of order to return
        explode: false
        in: path
        name: order_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Order not found
      summary: Find order by ID
      tags:
      - order
      x-openapi-router-controller: openapi_server.controllers.order_controller
    x-python-connexion-openapi-name: "/order/{orderId}"
  /pet:
    get:
      description: Returns list of pets
      operationId: get_pet_list
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Pet'
                type: array
            application/xml:
              schema:
                $ref: '#/components/schemas/Pet'
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Pet not found
      security:
      - api_key: []
      - petstore_auth:
        - write:pets
        - read:pets
      summary: Get list of all pets
      tags:
      - pet
      x-openapi-router-controller: openapi_server.controllers.pet_controller
    post:
      description: Add a new pet to the store
      operationId: add_pet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
        description: Create a new pet in the store
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
            application/xml:
              schema:
                $ref: '#/components/schemas/Pet'
          description: Successful operation
        "405":
          description: Invalid input
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      summary: Add a new pet to the store
      tags:
      - pet
      x-openapi-router-controller: openapi_server.controllers.pet_controller
    put:
      description: Update an existing pet by Id
      operationId: update_pet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
        description: Update an existent pet in the store
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
            application/xml:
              schema:
                $ref: '#/components/schemas/Pet'
          description: Successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Pet not found
        "405":
          description: Validation exception
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      summary: Update an existing pet
      tags:
      - pet
      x-openapi-router-controller: openapi_server.controllers.pet_controller
  /pet/{pet_id}:
    delete:
      description: delete a pet
      operationId: delete_pet
      parameters:
      - description: Pet id to delete
        explode: false
        in: path
        name: pet_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
            application/xml:
              schema:
                $ref: '#/components/schemas/Pet'
          description: successful operation
        "400":
          description: Invalid pet value
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      summary: Deletes a pet
      tags:
      - pet
      x-openapi-router-controller: openapi_server.controllers.pet_controller
    get:
      description: Returns a single pet
      operationId: get_pet
      parameters:
      - description: ID of pet to return
        explode: false
        in: path
        name: pet_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
            application/xml:
              schema:
                $ref: '#/components/schemas/Pet'
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Pet not found
      security:
      - api_key: []
      - petstore_auth:
        - write:pets
        - read:pets
      summary: Find pet by ID
      tags:
      - pet
      x-openapi-router-controller: openapi_server.controllers.pet_controller
    x-python-connexion-openapi-name: "/pet/{petId}"
  /product:
    get:
      description: Returns list of products
      operationId: get_product_list
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Product'
                type: array
            application/xml:
              schema:
                $ref: '#/components/schemas/Product'
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Product not found
      summary: Get list of all products
      tags:
      - product
      x-openapi-router-controller: openapi_server.controllers.product_controller
    post:
      description: Add a new Product to the store
      operationId: add_product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/xml:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
        description: Create a new Product in the store
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
            application/xml:
              schema:
                $ref: '#/components/schemas/Product'
          description: Successful operation
        "405":
          description: Invalid input
      summary: Add a new Product to the store
      tags:
      - product
      x-openapi-router-controller: openapi_server.controllers.product_controller
    put:
      description: Update an existing Product by Id
      operationId: update_product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/xml:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
        description: Update an existent Product in the store
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
            application/xml:
              schema:
                $ref: '#/components/schemas/Product'
          description: Successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Product not found
        "405":
          description: Validation exception
      summary: Update an existing Product
      tags:
      - product
      x-openapi-router-controller: openapi_server.controllers.product_controller
  /product/{product_id}:
    delete:
      description: delete a Product
      operationId: delete_product
      parameters:
      - description: Product id to delete
        explode: false
        in: path
        name: product_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
            application/xml:
              schema:
                $ref: '#/components/schemas/Product'
          description: Successful operation
        "400":
          description: Invalid Product value
      summary: Deletes a Product
      tags:
      - product
      x-openapi-router-controller: openapi_server.controllers.product_controller
    get:
      description: Returns a single Product
      operationId: get_product
      parameters:
      - description: ID of Product to return
        explode: false
        in: path
        name: product_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
            application/xml:
              schema:
                $ref: '#/components/schemas/Product'
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Product not found
      summary: Find Product by ID
      tags:
      - product
      x-openapi-router-controller: openapi_server.controllers.product_controller
    x-python-connexion-openapi-name: "/product/{productId}"
  /user:
    get:
      description: Returns list of users
      operationId: get_user_list
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                type: array
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: User not found
      summary: Get list of all users
      tags:
      - user
      x-openapi-router-controller: openapi_server.controllers.user_controller
    post:
      description: Add a new user to the user
      operationId: add_user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
        description: Create a new user in the user
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
          description: Successful operation
        "405":
          description: Invalid input
      summary: Add a new user to the user
      tags:
      - user
      x-openapi-router-controller: openapi_server.controllers.user_controller
    put:
      description: Update an existing user by Id
      operationId: update_user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
        description: Update an existent user in the user
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
          description: Successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: User not found
        "405":
          description: Validation exception
      summary: Update an existing user
      tags:
      - user
      x-openapi-router-controller: openapi_server.controllers.user_controller
  /user/{user_id}:
    delete:
      description: delete a user
      operationId: delete_user
      parameters:
      - description: User id to delete
        explode: false
        in: path
        name: user_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
          description: successful operation
        "400":
          description: Invalid user value
      summary: Deletes a user
      tags:
      - user
      x-openapi-router-controller: openapi_server.controllers.user_controller
    get:
      description: Returns a single user
      operationId: get_user
      parameters:
      - description: ID of user to return
        explode: false
        in: path
        name: user_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: User not found
      summary: Find user by ID
      tags:
      - user
      x-openapi-router-controller: openapi_server.controllers.user_controller
    x-python-connexion-openapi-name: "/user/{userId}"
components:
  requestBodies:
    Pet:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
      description: Pet object that needs to be added to the store
    Order:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Order'
        application/xml:
          schema:
            $ref: '#/components/schemas/Order'
      description: Order object that needs to be added to the store
    User:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
        application/xml:
          schema:
            $ref: '#/components/schemas/User'
      description: User object that needs to be added to the store
    Category:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Category'
        application/xml:
          schema:
            $ref: '#/components/schemas/Category'
      description: Category object that needs to be added to the store
    Product:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Product'
        application/xml:
          schema:
            $ref: '#/components/schemas/Product'
      description: Product object that needs to be added to the store
  schemas:
    Order:
      example:
        quantity: 7
        id: 1
        shipDate: 2000-01-23T04:56:07.000+00:00
        complete: true
      properties:
        id:
          example: 1
          format: int64
          title: id
          type: integer
        quantity:
          example: 7
          format: int32
          title: quantity
          type: integer
        shipDate:
          format: date-time
          title: shipDate
          type: string
        complete:
          title: complete
          type: boolean
      title: Order
      type: object
      xml:
        name: order
    Category:
      example:
        name: Dog
        id: 1
      properties:
        id:
          example: 1
          format: int64
          title: id
          type: integer
        name:
          example: Dog
          title: name
          type: string
      title: Category
      type: object
      xml:
        name: category
    User:
      example:
        firstName: John
        lastName: James
        password: "12345"
        phone: "12345"
        id: 1
        email: john@xyz.com
        username: theUser
      properties:
        id:
          example: 1
          format: int64
          title: id
          type: integer
        username:
          example: theUser
          title: username
          type: string
        firstName:
          example: John
          title: firstName
          type: string
        lastName:
          example: James
          title: lastName
          type: string
        email:
          example: john@xyz.com
          title: email
          type: string
        password:
          example: "12345"
          title: password
          type: string
        phone:
          example: "12345"
          title: phone
          type: string
      title: User
      type: object
      xml:
        name: user
    Pet:
      example:
        price: 10
        name: doggie
        id: 10
        breed: pug
        age: 2
      properties:
        id:
          example: 10
          format: int64
          title: id
          type: integer
        name:
          example: doggie
          title: name
          type: string
        breed:
          example: pug
          title: breed
          type: string
        age:
          example: 2
          format: int64
          title: age
          type: integer
        price:
          example: 10
          format: int64
          title: price
          type: integer
      required:
      - name
      title: Pet
      type: object
      xml:
        name: pet
    Product:
      example:
        quantity: 10
        price: 10
        name: dogFood
        id: 1
      properties:
        id:
          example: 1
          format: int64
          title: id
          type: integer
        name:
          example: dogFood
          title: name
          type: string
        quantity:
          example: 10
          format: int64
          title: quantity
          type: integer
        price:
          example: 10
          format: int64
          title: price
          type: integer
      title: Product
      type: object
  securitySchemes:
    petstore_auth:
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller_.info_from_petstore_auth
      x-scopeValidateFunc: openapi_server.controllers.security_controller_.validate_scope_petstore_auth
    api_key:
      in: header
      name: api_key
      type: apiKey
      x-apikeyInfoFunc: openapi_server.controllers.security_controller_.info_from_api_key
